build:
	sh tools/scripts/build.sh
prepare:
	sh tools/scripts/prepare.sh
clean:
	rm -rf out/
setup:
	mkdir ${PWD}/files/debian
	wget https://drive.google.com/uc?export=download&id=0B1BaegXXFI73UUZNS1R5OFVfT0k
	

